/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class monalisabot_StopFromKeyboard */

#ifndef _Included_monalisabot_StopFromKeyboard
#define _Included_monalisabot_StopFromKeyboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     monalisabot_StopFromKeyboard
 * Method:    isKeyPressed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_monalisabot_StopFromKeyboard_isKeyPressed
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
